
- hosts: "ec2-13-234-238-129.ap-south-1.compute.amazonaws.com"
  tasks:
      
    - name: "installing httpd"
      yum: 
        name: "httpd"
        state: present
         
    - name: "copying content to /var/www/html/"
      copy: 
        content: "Hello Ansible Tower"
        dest: "/var/www/html/ansible-tower.html"
        
    - name: "starting nginx server"
      service:
         name: "httpd"
         state: restarted
